# Generated by Django 4.1.4 on 2023-02-28 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_images')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_amount', models.IntegerField()),
                ('current_amount', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField()),
                ('video_link', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='campaigns', to='campaign.image')),
                ('investors', models.ManyToManyField(blank=True, related_name='invested_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
