# Generated by Django 4.1.4 on 2023-03-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
