# Generated by Django 4.1.4 on 2023-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
