# Generated by Django 4.1.4 on 2023-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_campaign_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pitch_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/pitches'),
        ),
    ]
