# Generated by Django 4.1.4 on 2023-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_campaign_pitch_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
    ]
