# Generated by Django 4.1.4 on 2023-03-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaign_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
